services:
  - type: web
    name: leaderboard-backend
    env: node
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health 